version: '3.4'

x-common-variables: &common-variables
  DATASOURCE_HOST: ${DB_HOST}
  DATASOURCE_USER: ${DB_USER}
  DATASOURCE_PASSWORD: ${DB_PASSWORD}
  DATASOURCE_NAME: ${DB_DATABASE}
  DATASOURCE_PORT: ${DB_PORT}

services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mystorage:/var/lib/mysql

  shipping:
    build:
      context: . #shippingsystem
      dockerfile: shipping/Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "2222:2222"
    restart: always
    environment:
      <<: *common-variables

  zookeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
    depends_on:
      - zookeper

volumes:
  mystorage: